image: python:2

before_script:
  - pip install -U platformio
  - platformio update

test:
  stage: test
  script:
    - platformio ci --project-conf=platformio.ini src

compile:
  stage: build
  script:
    - platformio run
  artifacts:
    untracked: true
    paths:
    - .pioenvs

deploy:
  stage: deploy
  only:
    - tags
  dependencies:
    - compile
  script:
    - apt-get -y update
    - apt-get -y install p7zip-full
    - mkdir dist
    - cp .pioenvs/megaatmega2560/firmware.hex dist/mhns-bs-fw-mega2560-${CI_COMMIT_TAG}.hex
    - cd dist
    - 7z a ../mhns-bs-fw-mega2560-${CI_COMMIT_TAG}.zip *
  artifacts:
    paths:
      - dist
      - mhns-bs-fw-mega2560-${CI_COMMIT_TAG}.zip
